apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      labels:
        app: cms
    spec:
      containers:
      - name: cms
        image: 482053628475.dkr.ecr.eu-central-1.amazonaws.com/usupport-cms
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: cms-secrets
        - configMapRef:
            name: cms-config
        ports:
        - containerPort: 1337
      imagePullSecrets:
      - name: regcred
